apiVersion: v1
kind: Service
metadata:
  name: project
spec:
  type: NodePort
  selector:
    app: project
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 8080
