apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercise
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
      tier: backend
  template:
    metadata:
      labels:
        app: project
        tier: backend
    spec:
      containers:
        - name: backend
          image: PROJECT/IMAGE_BACKEND
          env:
          - name: NATS_URL
            value: nats://my-nats:4222
          envFrom:
          - secretRef:
              name: postgres-secret
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercise
  name: frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
      tier: frontend
  template:
    metadata:
      labels:
        app: project
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: PROJECT/IMAGE_FRONTEND
          env:
          - name: BACKEND_URL
            value: http://backend-svc:8080
