apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercise
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: PROJECT/IMAGE_BACKEND
          envFrom:
          - secretRef:
              name: postgres-secret
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
        - name: frontend
          image: PROJECT/IMAGE_FRONTEND
