apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: exercise
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA3KOm/siiOYs25PSDXIECWpZvS7n1HEseHAfOt4AT5oEWv00cOIaTycdslbebM/LKFEgBFku3YQUaK/nUe1nuMbKNHXcs/c5lBdiVQdHHoQmWhES25kKFtKvDA0bzyBbAdcr41Bd3x9M7t41ZJZkbM/4qYMWt7ZQWlp6QxnPU8nb++OLKSchw74dA1Z2REyj6kdPBqj+aPU+Y7+vdk5GZG//R2FAO03JIgcQ8dH5ZTKluh4+TEBHnjqqHElgDSzbwPAC7TS1q6wVIPCUawhcnfPNtpTwBFYSOZcwZris4PNomFW8fSqJPzr1nvl55jmGJNiS8Wmlke9T1CSLfEaS4D2VZgtd42Zda4juYVC9qUMAn+1fiPGWSHdgRMRb/fJvEFCrqiWHswdb+DVebbwXhPTHDjmwq0+TvLnZwfvFwTIEDuK59GMIidA/VDjBpej3T7M0i9x1640knHxHUePeW2irjXx78znHHEvrc1J7iXqIfCfELUr2o2Ks2Opc/Zx/dbgSHHcznAAWR9VLbEWf62Y6EYa0Vj/D7SBi1NHJLb9bNbpkT2YyY9gPqhBEpDzjGvGhbuo2firG8j15PiP/qDonrdmQLKag7Es0WnROUnfweOVjVHw+VnpAmn/jbMg9q5gZ1YGyIfXU6osY/DOb0DBGtAOCewURQL5mrvB3L3M4q2dcEUtzD+HbiB0JRaZvN6qBIPjr9+UQ==
    POSTGRES_USER: AgBn0FRoq0bdEaeequNRULju0EjWKRYlQswEejjD6GZZUuX0nRjuuk7BY0s6nqxvKYEWBmSb/bo21rJnQPrBnRA8QqsyVJiHe5MLMcZKYlJpyamtP5GMR5YQYAqD+J2fGIrQsNgUX1L5AnQCJAHRm6BZShIXg7e+Ds7SWCKgtk3ahMavD9RZ8bnyfH5z+0klgV3dvdqfAv36OlsoIQqaAjfWs2uiLcq4FRiRcXxUkqkSw+Jfq7O8WEys+RIBghaKOyma1AQGjf9+dZe5FeA2JkkwYOZ8jcFSJofU+dWARB5cioH73IUvz3xNCf1PCwb6KG4zM50hyb3rRWG1wKY75J/66QiR+ueUdiNG3i6lNJSzU1L1R+ZT7Q0Th26mIFzJnC8k9GZNXkzfZhBgIj+R90L/fmXKp8onDjoid4WwLMIXj+suQcaCZwULnFyFIYzHeA45l+R+Q3UNiirK3GB6eVOiR5iVZ0gIPLryVOf0/7LJroyMJiNQrQtr31PhnMSQWKeBmvF7zFg2F2rKeAzpKMdyad1JNzMapywpBNDBBOtMq0vlsHk38DhaIeo1H6oomjSbJpuykvEnfqtDgtom5bdYRtDnYkMuW/VqjhGueyioHo6LeIZxxe1EPFu11SxQoRUpW+j4sb8CZdgukgNZ6/L6DCZQf4DIc0v4WUXk4nnaq7/e8WulnBWAzMz+wEL9zG1TMhtxu8NUlQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: exercise

