apiVersion: v1
kind: Service
metadata:
  namespace: exercise
  name: postgres-svc
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: exercise
  name: postgres-ss
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
          - secretRef:
                name: postgres-secret
          ports:
          - name: postgres-port
            containerPort: 5432
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
            subPath: postgres
  volumeClaimTemplates:
    - metadata:
        namespace: exercise
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
