apiVersion: v1
kind: Service
metadata:
  namespace: exercise
  name: backend-svc
spec:
  clusterIP: None
  selector:
    app: project
    tier: backend
  ports:
    - port: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: exercise
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: project
    tier: frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
