apiVersion: v1
kind: Service
metadata:
  namespace: exercise
  name: backend-svc
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
