apiVersion: v1
kind: Service
metadata:
  namespace: exercise
  name: backend-svc
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - targetPort: 8080
      protocol: TCP
      port: 2345
