apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: main-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-app
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
