apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: exercise
  name: daily-todo
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            image: dhanusaputra/cronjob
            env:
              - name: URL
                value: "http://backend-svc:8080/query"
          restartPolicy: OnFailure
