apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: exercise
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBI2A7yWWOBKM4/p8ids2iCdBdE3ZH/neRnrzS2d0JmJpm47BD5TmvnDikTPmTOLZVFpHyzjU2hrNzFun6Pt3I3pjZDa2I0FFgSGNRagZjfQlxJZGEcvv9ZE0AWV1LyNYy64I+JN8+wbAK7zuCXkXwU9qKsMOKT0ZQJZT6AFs3dS5wHi0u/MCcKomFxAThsX2bQbcGlCReBsMbnhhSIokSuQ05Ar9s+63RvQpx7dZJ//dHHGcs7EaPpsSXxR2aykRiXOZ78JdE+u7k5v7l14I7ftCvWP1OqziW4KHqKXuIa2iTlte2W6tHfdCl5WbVHstvsXZgv1/aweVV6qlTib8gOw5nFHbDMXBgl5o1+VOuTuEYflVR1RFbdLoK/kKEf4o2Xrml3ReVGCFM+YFJAfJfXKHRqRi6Yk0IRKsOo3PIGDCZEEFXSm+agG9aLm11g/qLObFQSZfn77cYOSOu9rM4koD463LwB1I8ayGx2kPL/QKVc71HU4yDEEk6cSqwdB9rxDl6yp8Fq9VtW6YIUedwUt2ypdwzCYQ+0tQOLiBltS/hM+8HPdNavKmaEznYvSLttxHJdRpi2+9ueA9/lZ/fq6dXZUp5T0jjqiMShNjpvTHDDMpzBxzDaPAmDO1YeGFuzBYX693mO70q5oatG0R7yXzy0bx9h0t7wajdcN1XXj1/ygdc5b29ULk/NJnrcy++xF1u2xU8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: exercise

