apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong-app
spec:
  template:
    metadata:
      name: pingpong-app
    spec:
      containers:
        - image: dhanusaputra/pingpong_app
          env:
            - name: PINGPONG_PORT
              value: "8080"
        - image: dhanusaputra/main-app
          env:
            - name: APP_PORT
              value: "5000"
