apiVersion: v1
kind: Service
metadata:
  namespace: exercise
  name: pingpong-app
spec:
  type: ClusterIP
  selector:
    app: pingpong-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
