apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/postgres-sealedsecret.yaml
- manifests/postgres-statefulset.yaml
- manifests/deployment.yaml
- manifests/service.yaml
images:
- name: PROJECT/IMAGE_BACKEND
  newName: dhanusaputra/backend
- name: PROJECT/IMAGE_FRONTEND
  newName: dhanusaputra/frontend
namespace: exercise
