name: Delete application

on:
  delete:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: asia-southeast2-b
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  delete:
    name: Delete
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - run: gcloud --quiet auth configure-docker

    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Delete
      run: |-
        kubectl delete namespace ${GITHUB_REF#refs/heads/} || true
